### ISSUE TITLE
[Question] Adding additional values

### ISSUE THREAD

**Issue by cosmo84** [B-Virtual/node-red-contrib-atag-one#2]
Hi,

what about adding the values:

burningHours
boilerHeatingFor

Should be possible without big effort, right?

Many thanks,

Stephan

**Comment by B-Virtual** [comment]
Hi,

BurningHours is already present. What do you mean by BoilerHeatingFor?

You mean the time to get to heating temp? It has ch_time_to_temp.

**Comment by cosmo84** [comment]
Hi,

maybe I got the parameters wrong. What I have in mind is the status, if the heating is currently on. Something like flame status, and if it is on for hot water (shower etc.) or the room heating. 

Thanks,

Stephan
